### ISSUE TITLE
multi-file rar-archive with naming part01,part02,part03 not processed/showed correctly

### ISSUE THREAD

**Issue by vchrizz** [plajjan/pyarrfs#8]
when accessing a multi-file rar archive with naming style like following, earch rar file is shown as own folder and is empty:
file.part01.rar
file.part02.rar
file.part03.rar

same for this:
file.part1.rar
file.part2.rar
file.part3.rar

expected would be to see the content of the archive within at least one of those folders.

**Comment by vchrizz** [comment]
not sure if this is wrong behaviour of pyarrfs or rarfile itself.
created issue for rarfile too: https://github.com/markokr/rarfile/issues/40

**Comment by vchrizz** [comment]
sorry, my bad, a file was missing from the archive, accessing the first volume works as expected if the archive is complete.

**Comment by plajjan** [comment]
Hehe ok. Nice to hear someone is using it :)
